include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: true
linter:
  rules:
    - public_member_api_docs
    - type_annotate_public_apis
    - void_checks
    - unnecessary_new
