name: fuzzy
version: 0.4.1

description: Fuzzy search in Dart. Initially a code conversion, subset of Fuse.js.
homepage: https://github.com/tomasweigenast/fuzzy

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  async_task: ^1.0.17
  latinize: ^0.1.0-nullsafety

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1